[project]
name = "machine-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ahmad Hafid (Ocinz)", email = "ahmadhafid28632@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "scikit-learn>=1.9.0",
]

[project.scripts]
machine-learning = "machine_learning:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"
